# --- STAGE 1: Build ---
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

# --- STAGE 2: Runner (Production Image) ---
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
# Essential for Docker networking: Binds to 0.0.0.0 instead of localhost
# ensuring the container is accessible from outside (e.g. by Playwright)
ENV HOSTNAME="0.0.0.0"

# Security: Don't run as root user
# We create a specific user/group with ID 1001 to run the application
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy only public assets (images, fonts, etc.)
COPY --from=builder /app/public ./public

# Copy the optimized "Standalone" build
# This feature (enabled in next.config.ts) creates a minimal folder
# containing only the necessary files for production, reducing image size by ~80%.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs

EXPOSE 3000

# Start the optimized server (server.js is generated by 'output: standalone')
CMD ["node", "server.js"]
